# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: football-gossip

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

custom:
  pythonRequirements:
    dockerizePip: non-linux
  defaultStage: sandbox

provider:
  name: aws
  runtime: python3.6
  stage: ${opt:stage, self:custom.defaultStage}
  region: eu-west-1

package:
  exclude:
    - node_modules/**
    - env/**
    - tests/**


functions:
  gossip:
    handler: handler.handler

plugins:
  - serverless-python-requirements


